- name: 确认 kubelet 已停止运行
  service:
    name: kubelet
    state: stopped
    enabled: yes

- name: 更新 certs 证书
  shell: kubeadm init phase upload-certs --upload-certs | tail -n 1 | sed s/[[:space:]]//g
  register: certs
  run_once: True
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: 更新变量 kubeadm_certskey
  set_fact:
    certificate_key: "{{ certs.stdout }}"
  run_once: True
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: 创建 kubeadm join 配置文件
  template:
    src: kube-join.yml.j2
    dest: "/etc/kubernetes/kubeadm-join.yml"
    owner: root
    mode: 0644

- name: 其他 master 节点加入集群
  shell: kubeadm join --config=/etc/kubernetes/kubeadm-join.yml
  register: join_result
  until: join_result is success
  retries: 12
  delay: 10

- block:
  - name: 创建 kubeconfig 目录
    file: 
      name: "{{ item }}"
      state: directory
    with_items:
    - "{{ ansible_env.PWD }}/.kube"
    - "{{ ansible_env.HOME }}/.kube"
    
  - name: 复制 kubeconfig 文件到 .kube 目录
    copy:
      src: /etc/kubernetes/admin.conf
      dest: "{{ item }}/config"
      mode: 0600
      remote_src: yes
    with_items:
    - "{{ ansible_env.PWD | default('/root') }}/.kube"
    - "{{ ansible_env.HOME | default('/root') }}/.kube"

  - name: 设置 kubeconfig 文件权限
    file:
      path: "{{ ansible_env.PWD | default('/root') }}/.kube/config"
      owner: "{{ ansible_env.SUDO_USER | default('root') }}"
      mode: '0600'
  when: inventory_hostname in (groups['kube-master'] + groups['new-master'])
