---
- name: Create file share dir
  become: true
  file:
    path: "{{ desktop_mount_dir }}"
    state: directory
    mode: 0755

- name: Create file share_image dir
  become: true
  file:
    path: "{{ desktop_mount_dir }}/voi/share_image"
    state: directory
    mode: 0755

- name: copy init share images file
  become: true
  copy:
    src: "{{ item }}"
    dest: "{{ desktop_mount_dir }}/voi/share_image"
  loop:
    - "5GDISK.qcow2"
    - "10GDISK.qcow2"
    - "50GDISK.qcow2"
    - "100GDISK.qcow2"
    - "200GDISK.qcow2"
    - "500GDISK.qcow2"

- name: only deploy voi mount data device
  block: 
  - name: Create directory if not exists
    file:
      name: "{{ voi_data_directory }}"
      state: directory
      owner: root
      group: root
      mode: '0751'

  - name: format datanode disks
    filesystem: 
      fstype: ext4
      force: true
      dev: "{{ voi_data_device }}"

  - name: mount datanode disks
    mount:
      path: "{{ voi_data_directory }}"
      src: "{{ voi_data_device }}"
      fstype: ext4
      opts: "defaults,noatime,nobarrier"
      state: mounted
  when: 
    - ansible_facts.mounts | selectattr('mount', '==', voi_data_directory) | list | length == 0 
    - voi_data_device != ""