imagePullSecrets: 
  - name: docker-register-secrets
driverName: local.csi.openebs.io

nodeplugin:
  priorityClassName: ""
  registrar:
    name: csi-node-driver-registrar 
    image: 
      repository: 172.18.31.155/kubernetes/csi-node-driver-registrar
      tag: latest
      pullPolicy: IfNotPresent
    resources: {}

  plugin:
    name: openebs-lvm-plugin
    image:
      repository: 172.18.31.155/kubernetes/lvm-driver
      tag: latest
      pullPolicy: IfNotPresent 
    resources: {}


provisioner:
  replicaCount: 1
  priorityClassName: ""
  provisioner:
    name: csi-provisioner
    image:
      repository: 172.18.31.155/kubernetes/csi-provisioner
      tag: latest
      pullPolicy: IfNotPresent
    resources: {}

  resizer:
    name: csi-resizer
    image:
      repository: 172.18.31.155/kubernetes/csi-resizer
      tag: latest
      pullPolicy: IfNotPresent
    resources: {}

  snapshotter:
    name: csi-snapshotter
    image:
      repository: 172.18.31.155/kubernetes/csi-snapshotter
      tag: latest
      pullPolicy: IfNotPresent
    resources: {}

  controller:
    name: snapshot-controller
    image:
      repository: 172.18.31.155/kubernetes/snapshot-controller
      tag: latest
      pullPolicy: IfNotPresent
    resources: {}

service:
  port: 9500

storageClass:
  # Specifies whether the Storage class should be created
  create: true
  name: openebs-lvmpv
  volgroup: lvmvg
  storage: lvm

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80




