apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: libvirt
    app.kubernetes.io/component: libvirt
    app.kubernetes.io/release_group: libvirt
  name: libvirt
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: libvirt
      app.kubernetes.io/component: libvirt
      app.kubernetes.io/release_group: libvirt
  template:
    metadata:
      labels:
        app.kubernetes.io/name: libvirt
        app.kubernetes.io/component: libvirt
        app.kubernetes.io/release_group: libvirt
    spec:
      tolerations:
        - key: node.kubernetes.io/not-ready
          effect: NoExecute
          tolerationSeconds: {{ .Values.tolerationSeconds }}
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: {{ .Values.tolerationSeconds }}
      containers:
      - name: libvirt
        image: "{{ .Values.image.libvirt }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        lifecycle:
          preStop:
            exec:
              command:
                - bash
                - -c
                - kill $(cat /var/run/libvirtd.pid)
        livenessProbe:
          exec:
            command:
              - bash
              - -c
              - /usr/bin/virsh list
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 30
        readinessProbe:
          exec:
            command:
              - bash
              - -c
              - /usr/bin/virsh list
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        securityContext:
          privileged: true
          runAsUser: 0
          runAsGroup: 0
          readOnlyRootFilesystem: false
        {{- if .Values.enableHugepages }}
        resources:
          limits:
            hugepages-2Mi: {{ .Values.hugepages_2M_total }}Gi
            memory: 2Gi
          requests:
            memory: 2Gi
        {{- end }}
        volumeMounts:
          - mountPath: /etc/localtime
            name: localtime
          {{- if .Values.enableHugepages }}
          - mountPath: /hugepages-2Mi
            name: hugepage-2mi
          {{- end }}
          - mountPath: /etc/libvirt/qemu.conf
            name: libvirt-etc
            readOnly: true
            subPath: qemu.conf
          - mountPath: /etc/libvirt/libvirtd.conf
            name: libvirt-etc
            readOnly: true
            subPath: libvirtd.conf
          - mountPath: /etc/vdi/vdi_conf.ini
            name: libvirt-etc
            readOnly: true
            subPath: vdi_conf.ini
          - mountPath: /etc/libvirt/qemu
            name: etc-libvirt-qemu
          - mountPath: /lib/modules
            name: libmodules
            readOnly: true
          - mountPath: /var/lib/libvirt
            mountPropagation: Bidirectional
            name: var-lib-libvirt
          - mountPath: /run
            name: run
          - mountPath: /dev
            name: dev
          - mountPath: /sys/fs/cgroup
            name: cgroup
          - mountPath: /etc/machine-id
            name: machine-id
            readOnly: true
          - mountPath: {{ .Values.trochilus_dir }}
            mountPropagation: Bidirectional
            name: share-dir
          {{- if .Values.enable_ceph }}
          - mountPath: /etc/libvirt/secrets
            name: secret-dir
          - mountPath: /etc/ceph
            mountPropagation: Bidirectional
            name: etc-ceph
          - mountPath: /etc/libvirt/secrets/{{ .Values.secret.rbd_secret_uuid }}.xml
            name: libvirt-etc
            readOnly: true
            subPath: {{ .Values.secret.rbd_secret_uuid }}.xml
          - mountPath: /etc/libvirt/secrets/{{ .Values.secret.rbd_secret_uuid }}.base64
            name: libvirt-etc
            readOnly: true
            subPath: {{ .Values.secret.rbd_secret_uuid }}.base64
          {{- end }}
      dnsPolicy: ClusterFirstWithHostNet
      hostIPC: true
      hostNetwork: {{ .Values.hostNetwork }}
      hostPID: true
      restartPolicy: Always
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
      {{- end }}
      serviceAccount: libvirt
      serviceAccountName: libvirt
      priorityClassName: {{ .Values.priorityClassName }}
      volumes:
        - emptyDir: {}
          name: secret-dir
        {{- if .Values.enableHugepages }}
        - name: hugepage-2mi
          emptyDir:
            medium: HugePages-2Mi
        {{- end }}
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
        - name: libvirt-etc
          configMap:
            defaultMode: 292
            name: libvirt-etc
        - hostPath:
            path: /lib/modules
            type: ""
          name: libmodules
        - hostPath:
            path: /var/lib/libvirt
            type: ""
          name: var-lib-libvirt
        - hostPath:
            path: /run
            type: ""
          name: run
        - hostPath:
            path: /dev
            type: ""
          name: dev
        - hostPath:
            path: /sys/fs/cgroup
            type: ""
          name: cgroup
        - hostPath:
            path: /etc/machine-id
            type: ""
          name: machine-id
        - hostPath:
            path: /etc/libvirt/qemu
            type: ""
          name: etc-libvirt-qemu
        - hostPath:
            path: {{ .Values.share_dir }}
            type: "DirectoryOrCreate"
          name: share-dir
        {{- if .Values.enable_ceph }}
        - hostPath:
            path: /etc/ceph
            type: ""
          name: etc-ceph
        {{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 -}}
{{- end -}}
