apiVersion: v1
kind: Service
metadata:
  name: {{ include "btserver.fullname" . }}
  labels:
    {{- include "btserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.containers.port_btserver }}
      targetPort: btserver
      protocol: TCP
      name: btserver
    - port: {{ .Values.containers.port_track }}
      targetPort: btserver-track
      protocol: TCP
      name: btserver-track
  selector:
    {{- include "btserver.selectorLabels" . | nindent 4 }}
