- import_tasks: create_swap_file.yaml
  when:
    - create_swap_file | bool

- import_tasks: create_mount_crontab.yaml
  when:
    - enable_ceph | bool

- name: 获取 osd 数量
  shell: systemctl | grep running | grep osd@ | wc -l
  register: osd_num
  when:
    - enable_hugepages | bool

- name: 获取可分配的大页数量
  set_fact:
    hugepages_total: "{{ (ansible_memtotal_mb  - reserved_osd_memory_mb * osd_num.stdout | int - reserved_mds_memory_mb - reserved_mon_memory_mb - reseverd_system_memory_mb - reserved_host_memory_mb // 2) | int }}"
  when:
    - enable_hugepages | bool

- name: 复制开机执行脚本 reboot-script.sh
  template:
    src: reboot-script.sh.j2
    dest: /etc/kubernetes/reboot-script.sh
    mode: 755
  when:
    - ansible_distribution == "openEuler"

- name: 设置开机启动 iptables 命令
  become: true
  copy:
    src: iptables-accept.service
    dest: /usr/lib/systemd/system/
  when:
    - ansible_distribution == "openEuler"

- name: Reload systemctl and enable iptables-accept service
  become: true
  systemd:
    name: iptables-accept
    daemon_reload: true
    enabled: true
  when:
    - ansible_distribution == "openEuler"

- name: 执行 etcd 备份命令
  shell: /usr/local/bin/etcdtools backup
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: copy mariadb-backup job file
  template:
    src: mysql-backup.yaml.j2
    dest: /etc/kubernetes/plugins/mariadb/mysql-backup.yaml
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: 执行 mysql 备份任务
  shell: kubectl apply -f /etc/kubernetes/plugins/mariadb/mysql-backup.yaml
  delegate_to: "{{ groups['kube-master'][0] }}"
