image:
  fsd: 172.18.31.155/kubernetes/fsd:latest
  fsd_job: 172.18.31.155/kubernetes/fsd_job:latest
  fsd_nginx: nginx:1.15.9
  pullSecrets: ""
  pullPolicy: "IfNotPresent"

serviceAccountName: fsd
replica: 1
nodeSelector:
  control_role: enabled
priorityClassName: ""
hostNetwork: ""
tolerationSeconds: 30

service:
  fsd_webhook:
    port: 9010
    name: fsd-webhook
  fsd_job:
    port: 9011
    name: fsd-job
  fsd_tcp:
    port: 9012
    name: fsd-tcp
  fsd_tcp_file:
    port: 9013
    name: fsd-tcp-file
  fsd_nginx:
    port: 80
    name: fsd-web

mount_dir:
  fsd_log: /var/log/fsd
  prometheus_rule: /mnt/prometheus/rules
  alertmanager_conf: /mnt/prometheus/alertmanager
  share_dir: "/data/fsd"
  fsd_static: "/data/fsd/static"

fsd_env:
  redis_password: zhuolang@Troila@123
  redis_master_name: mymaster
  redis_sentinel_port: 26379
  redis_server_address: redis.default.svc.cluster.local
  mariadb_server_address: mariadb.default.svc.cluster.local
  emqx_server_address: emqx.default.svc.cluster.local
  thanos_server_address: thanos-query.default.svc.cluster.local
  fsd_job_server_address: fsd-job.default.svc.cluster.local
  trochilus_server_address: trochilus-api.default.svc.cluster.local
  btserver_server_address: btserver.default.svc.cluster.local
  netty_codec_mac: 60f81dad19ae
  deploy_mode: all
  proxy_ip: 172.18.28.222
  proxy_port: 9000
  deploy_vip: 172.18.28.222
  vnc_port: 9003
  desktop_bt_port_start: "6880"
  desktop_bt_port_end: "6889"
  share_root_path: "/mnt"
  cloud_disk_root_path: "/mnt/111"
  cloud_disk_share_disk_path: "ShareA"
  cloud_disk_username: "troila"
  cloud_disk_password: "Troila12"

fsd_job_env:
  mariadb_username: root
  mariadb_password: 123456

containerPath:
  sharedir: ""
  nginx_path: ""
